container:
  image: golang:latest
  cpu: 2
  memory: 4G

test_task:
  env:
    GO111MODULE: on
  get_script: go get -v ./...
  test_script: 
  # - go test -v -cover -coverprofile=coverage.txt -covermode=atomic -race ./...
  - ./.test.sh
  - bash <(wget https://codecov.io/bash  -q -O -)