language: go

go:
  - "1.11.x"
  - master
  - tip

os:
  - linux
  - osx

# go_import_path: github.com/alexandrestein/gotinydb

dist: trusty
sudo: false

install: true

script:
  - export GO111MODULE=on 
  - go vet ./...
  - go test -v -cover -race ./...

