language: go

go_import_path: github.com/alexandrestein/gotinydb

go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - master
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./test_script.sh  

after_success:
  - bash <(curl -s https://codecov.io/bash)
