language: go

go_import_path: github.com/alexandrestein/gotinydb

sudo: required 

go:
  - "1.10.x"
  - master
  - tip

before_install:
  - go get -t ./...

script:
  - go test -timeout 1h -v -failfast -race -coverprofile=coverage.txt -covermode=atomic

